version: '3.8'
services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - 80:80
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./env_variables.env
    volumes:
      - ./data:/var/lib/postgresql/data