  pytest1:
    build:
      context: .
      dockerfile: Dockerfile1
    volumes:
      - ./allure-results:/allure-results
    command: ["pytest", "tests/test1.py", "-s", "--junitxml=/allure-results/result1.xml"] // --alluredir=/allure-results/pytest2

  pytest2:
    build:
      context: .
      dockerfile: Dockerfile2
    volumes:
      - ./allure-results:/allure-results
    command: ["pytest", "tests/test2.py", "-s", "--junitxml=/allure-results/result2.xml"]
